/**
 * Tally data model.
 *
 * Every piece of user data is a "document": a plain JSON object with an `id`,
 * a `type` and a `rev` (hybrid logical clock revision, see hlc.ts). Documents
 * are the unit of storage, sync and conflict resolution (last-writer-wins by
 * `rev`). The full format is specified in docs/data-format.md — keep the two
 * in sync when changing anything here.
 */

export type ID = string;
/** Hybrid logical clock string, lexicographically ordered. See hlc.ts. */
export type Rev = string;
/** ISO 4217 currency code, e.g. "CAD". */
export type CurrencyCode = string;
/** Integer amount in the currency's minor unit (cents for CAD/EUR). */
export type Minor = number;
/** Local calendar date "YYYY-MM-DD". */
export type LocalDate = string;

export type DocType =
  | 'transaction'
  | 'merchant'
  | 'category'
  | 'tag'
  | 'paymentMethod'
  | 'budget'
  | 'recurring'
  | 'setting';

export interface BaseDoc {
  id: ID;
  type: DocType;
  rev: Rev;
  /** ISO 8601 UTC timestamp of creation. */
  createdAt: string;
  /** Tombstone. Deleted docs are kept so deletions sync. */
  deleted?: boolean;
}

export type TxKind = 'expense' | 'income' | 'refund';
export type Channel = 'in_person' | 'online';

export interface Split {
  /** Minor units, in the transaction's currency. Splits sum to the transaction amount. */
  amount: Minor;
  categoryId: ID | null;
  /** Extra tags for this part only (transaction tags always apply). */
  tagIds: ID[];
  note: string;
}

export interface Transaction extends BaseDoc {
  type: 'transaction';
  kind: TxKind;
  /** Local wall time with UTC offset, e.g. "2026-10-07T14:32:00-04:00". */
  occurredAt: string;
  /** Positive amount in minor units of `currency`. */
  amount: Minor;
  currency: CurrencyCode;
  /** Amount converted to `baseCurrency` (minor units). Equals amount when currencies match. */
  baseAmount: Minor;
  baseCurrency: CurrencyCode;
  merchantId: ID | null;
  /** What was bought. Optional; UI falls back to merchant name. */
  name: string;
  categoryId: ID | null;
  paymentMethodId: ID | null;
  channel: Channel | null;
  tagIds: ID[];
  description: string;
  purpose: string;
  /** When non-empty, the purchase is divided across categories. */
  splits: Split[];
  /** Set when generated by a recurring rule. */
  recurringId?: ID | null;
  /** Fingerprint of an imported bank row, used to skip duplicates. */
  importRef?: string | null;
  /** Raw statement text from a bank import. */
  bankDescription?: string | null;
}

export interface MerchantDefaults {
  categoryId: ID | null;
  paymentMethodId: ID | null;
  channel: Channel | null;
  tagIds: ID[];
  name: string;
  currency: CurrencyCode | null;
}

export interface Merchant extends BaseDoc {
  type: 'merchant';
  name: string;
  /** Lower-case substrings that identify this merchant in bank statements. */
  aliases: string[];
  defaults: MerchantDefaults;
  /** When true, saving a purchase updates `defaults` to what was entered. */
  learnDefaults: boolean;
  archived: boolean;
}

export interface Category extends BaseDoc {
  type: 'category';
  name: string;
  parentId: ID | null;
  /** Emoji or short text shown next to the name. */
  icon: string;
  /** Chart colour: categorical slot "slot:0".."slot:7" or a hex colour. */
  color: string;
  kind: 'expense' | 'income';
  order: number;
  archived: boolean;
}

export interface Tag extends BaseDoc {
  type: 'tag';
  name: string;
  color: string;
  archived: boolean;
}

export interface PaymentMethod extends BaseDoc {
  type: 'paymentMethod';
  name: string;
  /** Channel to assume when this method is picked and the merchant has none. */
  defaultChannel: Channel | null;
  order: number;
  archived: boolean;
}

/** Shared filter used by budgets, the transaction list, stats and widgets. */
export interface Filter {
  categoryIds?: ID[];
  tagIds?: ID[];
  merchantIds?: ID[];
  paymentMethodIds?: ID[];
  channels?: Channel[];
  kinds?: TxKind[];
  text?: string;
  minAmount?: Minor | null;
  maxAmount?: Minor | null;
}

export type PeriodUnit = 'day' | 'week' | 'month' | 'year';

export interface PeriodSpec {
  unit: PeriodUnit;
  /** Length in units, e.g. 2 + week = fortnightly. */
  count: number;
  /** Alignment date for count > 1. */
  anchor: LocalDate;
}

export interface Budget extends BaseDoc {
  type: 'budget';
  name: string;
  /** Limit in base-currency minor units. */
  amount: Minor;
  period: PeriodSpec;
  filter: Filter;
  /** Fraction (0..1) at which the budget shows a warning. */
  warnAt: number;
  icon: string;
  order: number;
  archived: boolean;
}

export type RecurringFreq = 'day' | 'week' | 'month' | 'year';

export interface Recurring extends BaseDoc {
  type: 'recurring';
  name: string;
  freq: RecurringFreq;
  interval: number;
  startDate: LocalDate;
  endDate: LocalDate | null;
  /** auto: create on the due date. confirm: show as "due" until confirmed or skipped. */
  mode: 'auto' | 'confirm';
  active: boolean;
  template: {
    kind: TxKind;
    amount: Minor;
    currency: CurrencyCode;
    merchantId: ID | null;
    name: string;
    categoryId: ID | null;
    paymentMethodId: ID | null;
    channel: Channel | null;
    tagIds: ID[];
    description: string;
    purpose: string;
    time: string; // "HH:MM"
  };
}

export interface Setting extends BaseDoc {
  type: 'setting';
  /** id is "setting:<key>" */
  key: string;
  value: unknown;
}

export type Doc =
  | Transaction
  | Merchant
  | Category
  | Tag
  | PaymentMethod
  | Budget
  | Recurring
  | Setting;

export type DocOf<T extends DocType> = Extract<Doc, { type: T }>;

/** Format version of exports and the sync payload. Bump on breaking changes. */
export const SCHEMA_VERSION = 1;
